# Generated by Django 2.0.7 on 2018-07-07 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='surveyresponse',
            unique_together={('ip', 'question')},
        ),
    ]
